### ISSUE TITLE
远控免杀

### ISSUE THREAD

**Issue by wsj20080820** [TideSec/BypassAntiVirus#15]
BypassAntiVirus
远控免杀系列文章及配套工具，汇总测试了互联网上的几十种免杀工具、113种白名单免杀方式、8种代码编译免杀、若干免杀实战技术，并对免杀效果进行了一—测试，为远控的免杀和杀软对抗免杀提供参考

**Comment by huoxu008** [comment]
免杀远控：飞机@dijia88888888
