### ISSUE TITLE
建议增加defender的免杀测试

### ISSUE THREAD

**Issue by hanc00l** [TideSec/BypassAntiVirus#2]
win10启用了AMSI的defender，已远远超越了传统的静态特征查杀和某数字公司的产品（通过以混淆和变形基本上很好过），需要从更深的技术层面进行绕过；建议在win10下，关闭defender的自动上传附件功能，测试这些方法是否能过运行时的查杀。

**Comment by TideSec** [comment]
virustotal.com里的"微软"就是指的windows defender，我表格里面也列出来它了，的确很多免杀技术都没法绕过它，目前(2019.12.25)只有两种方式能绕过。

**Comment by hanc00l** [comment]
。。。我也只找到两种方法能过

**Comment by TideSec** [comment]
别着急，后面还有20多种方法，肯定还有能过defender的。其实一个马不需要所有杀软都能过，能过你的目标主机上的杀软就足够了。^_^  
不过目前来看defender的确不太好过，还有瑞星也是很让人意外。。

**Comment by hanc00l** [comment]
期待有类似DotToJS这种新的技术，能绕过AMSI，期待精彩继续。。。
